# Generated by Django 2.2.28 on 2023-11-13 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilote', '0002_remove_character_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='photo',
        ),
    ]
