# Generated by Django 2.2.28 on 2023-11-14 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilote', '0004_auto_20231114_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='photo',
        ),
    ]
